'use client';

import React, { useState } from 'react';
import {
  AlertTriangle,
  CheckCircle2,
  Loader2,
  ShieldAlert,
  Users,
  X,
} from 'lucide-react';
import { AdminRegistrationItem, ActivationResultResponse } from '@/types';

interface ActivationModalProps {
  registration: AdminRegistrationItem;
  onConfirm: () => Promise<void>;
  onCancel: () => void;
  activationResult: ActivationResultResponse | null;
  isActivating: boolean;
  activationError: string | null;
}

export const ActivationModal: React.FC<ActivationModalProps> = ({
  registration,
  onConfirm,
  onCancel,
  activationResult,
  isActivating,
  activationError,
}) => {
  const [confirmed, setConfirmed] = useState(false);

  const handleConfirm = async () => {
    setConfirmed(true);
    await onConfirm();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/70 backdrop-blur-sm"
        onClick={!isActivating && !activationResult ? onCancel : undefined}
      />

      {/* Modal Panel */}
      <div className="relative w-full max-w-md bg-gray-900 border border-cyan-500/30 rounded-2xl shadow-2xl shadow-cyan-500/10 overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-800">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-lg bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
              <Users className="w-4 h-4" />
            </div>
            <h3 className="text-base font-bold text-white">
              {activationResult ? 'Team Activated ✓' : 'Activate Team'}
            </h3>
          </div>
          {!isActivating && !activationResult && (
            <button
              type="button"
              onClick={onCancel}
              className="p-1.5 rounded-lg text-gray-400 hover:text-white hover:bg-gray-800 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>

        <div className="p-6 space-y-5">
          {/* Success State */}
          {activationResult && (
            <div className="space-y-4">
              <div className="flex items-center space-x-3 p-4 rounded-xl bg-emerald-950/40 border border-emerald-500/40">
                <CheckCircle2 className="w-8 h-8 text-emerald-400 flex-shrink-0" />
                <div>
                  <p className="font-bold text-emerald-300 text-sm">Activation Successful</p>
                  <p className="text-xs text-gray-300 mt-0.5">
                    {registration.teamName} is now an active participant.
                  </p>
                </div>
              </div>

              {/* Team ID Display */}
              {activationResult.teamCode && (
                <div className="p-4 rounded-xl bg-gray-800/60 border border-gray-700 space-y-2">
                  <p className="text-[11px] text-gray-400 uppercase font-semibold tracking-wider">Official Team ID</p>
                  <p className="text-2xl font-black text-cyan-300 font-mono tracking-widest">
                    {activationResult.teamCode}
                  </p>
                  <p className="text-[11px] text-gray-400">
                    This is the team&apos;s authoritative identifier for event day operations.
                  </p>
                </div>
              )}

              {/* Credential Notice — PIN never shown */}
              <div className="p-3 rounded-xl bg-gray-800/40 border border-gray-700 text-xs text-gray-300 space-y-1">
                <p className="font-semibold text-white text-sm flex items-center space-x-1.5">
                  <ShieldAlert className="w-3.5 h-3.5 text-amber-400" />
                  <span>Credential Security Notice</span>
                </p>
                <p>
                  A 6-digit Team PIN has been generated by the backend and is{' '}
                  <strong className="text-white">not displayed here</strong> for security.
                </p>
                {activationResult.emailSent ? (
                  <p className="text-emerald-300 flex items-center space-x-1">
                    <CheckCircle2 className="w-3 h-3" />
                    <span>
                      Activation credentials have been dispatched to{' '}
                      <strong>{registration.leader.email}</strong>
                    </span>
                  </p>
                ) : (
                  <p className="text-amber-300 flex items-center space-x-1">
                    <AlertTriangle className="w-3 h-3" />
                    <span>
                      Activation succeeded but the credential email could not be delivered.
                      Use the &quot;Resend Credentials&quot; action on the registration details card.
                    </span>
                  </p>
                )}
              </div>

              <button
                type="button"
                onClick={onCancel}
                className="w-full py-3 rounded-xl bg-gray-800 hover:bg-gray-700 text-white font-semibold text-sm border border-gray-700 transition-all"
              >
                Close
              </button>
            </div>
          )}

          {/* Confirmation / Loading State */}
          {!activationResult && (
            <>
              {/* Team summary */}
              <div className="p-4 rounded-xl bg-gray-800/50 border border-gray-700 space-y-2">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-bold text-white text-base">{registration.teamName}</p>
                    <p className="text-xs text-gray-400 mt-0.5">
                      {registration.leader.name} · {registration.members.length + 1} members
                    </p>
                    <p className="text-xs text-gray-400">{registration.leader.email}</p>
                  </div>
                  <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-1 rounded bg-amber-500/10 text-amber-400 border border-amber-500/30">
                    REGISTERED
                  </span>
                </div>
              </div>

              {/* Explanation text */}
              {!confirmed && !isActivating && (
                <div className="space-y-3 text-sm text-gray-300">
                  <p className="font-semibold text-white">Activate this team?</p>
                  <p className="text-xs leading-relaxed">
                    Activation will generate the team&apos;s official{' '}
                    <strong className="text-white">Team ID</strong> and a new{' '}
                    <strong className="text-white">6-digit Team PIN</strong>. The credentials will be
                    sent to the team leader&apos;s registered email:{' '}
                    <span className="text-cyan-300 font-mono">{registration.leader.email}</span>
                  </p>
                  <p className="text-xs text-amber-300">
                    ⚠ This action cannot be undone. Only activate teams that are physically present at check-in.
                  </p>
                </div>
              )}

              {/* Loading state */}
              {isActivating && (
                <div className="flex items-center justify-center space-x-3 py-4">
                  <Loader2 className="w-6 h-6 text-cyan-400 animate-spin" />
                  <p className="text-sm text-cyan-300 font-semibold">Activating team on backend...</p>
                </div>
              )}

              {/* Error state */}
              {activationError && !isActivating && (
                <div className="p-3 rounded-xl bg-red-950/40 border border-red-500/40 text-xs text-red-300 flex items-start space-x-2">
                  <AlertTriangle className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="font-bold text-red-400">Activation Failed</p>
                    <p className="mt-0.5">{activationError}</p>
                  </div>
                </div>
              )}

              {/* Action Buttons */}
              {!isActivating && (
                <div className="flex space-x-3 pt-1">
                  <button
                    type="button"
                    onClick={onCancel}
                    className="flex-1 py-2.5 rounded-xl bg-gray-800 hover:bg-gray-700 text-gray-200 font-semibold text-sm border border-gray-700 transition-all"
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    onClick={handleConfirm}
                    disabled={isActivating}
                    className="flex-1 py-2.5 rounded-xl bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white font-bold text-sm border border-cyan-400/40 shadow-lg shadow-cyan-500/20 transition-all"
                  >
                    ACTIVATE TEAM
                  </button>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
};
